### ISSUE TITLE
Kubo crashes when loading plugin: fatal error: runtime: no plugin module data

### ISSUE THREAD

**Issue by emendir** [ipfs/go-ipfs-example-plugin#28]
I want to try building my own Kubo plugin, so I tried to run this demo first. I successfully compiled and installed this project using the following commands:
```sh
git clone https://github.com/ipfs/go-ipfs-example-plugin.git
cd go-ipfs-example-plugin
make go.mod IPFS_VERSION=v0.19.0
make build
make install
```

But now when I start Kubo v0.19.0 with `ipfs daemon`, it crashes immediately. Here is an excerpt of the ouput:
```
fatal error: runtime: no plugin module data

goroutine 1 [running]:
runtime.throw({0x281abe7?, 0xe643bb?})
	runtime/panic.go:1047 +0x5d fp=0xc0002ff328 sp=0xc0002ff2f8 pc=0xe3387d
plugin.lastmoduleinit()
	runtime/plugin.go:20 +0x8ce fp=0xc0002ff410 sp=0xc0002ff328 pc=0xe6420e
plugin.open({0xc0007164b0, 0x2e})
	plugin/plugin_dlopen.go:77 +0x3ef fp=0xc0002ff680 sp=0xc0002ff410 pc=0x1e6918f
plugin.Open(...)
	plugin/plugin.go:32
github.com/ipfs/kubo/plugin/loader.unixLoadPlugin({0xc0007164b0?, 0xe643bb?})
	github.com/ipfs/kubo@v0.20.0/plugin/loader/load_unix.go:20 +0x25 fp=0xc0002ff6f0 sp=0xc0002ff680 pc=0x2063725
github.com/ipfs/kubo/plugin/loader.loadDynamicPlugins.func1({0xc0007164b0, 0x2e}, {0x2bff608, 0xc0001f76c0}, {0x0?, 0x0?})
	github.com/ipfs/kubo@v0.20.0/plugin/loader/loader.go:206 +0x1af fp=0xc0002ff7e8 sp=0xc0002ff6f0 pc=0x20646af
path/filepath.walk({0xc0007164b0, 0x2e}, {0x2bff608, 0xc0001f76c0}, 0xc0002ffa10)
	path/filepath/path.go:434 +0x123 fp=0xc0002ff8b0 sp=0xc0002ff7e8 pc=0xf18343
path/filepath.walk({0xc000512d00, 0x1c}, {0x2bff608, 0xc0001f75f0}, 0xc0002ffa10)
	path/filepath/path.go:458 +0x285 fp=0xc0002ff978 sp=0xc0002ff8b0 pc=0xf184a5
path/filepath.Walk({0xc000512d00, 0x1c}, 0xc0002ffa10)
	path/filepath/path.go:521 +0x6c fp=0xc0002ff9c8 sp=0xc0002ff978 pc=0xf1860c
github.com/ipfs/kubo/plugin/loader.loadDynamicPlugins({0xc000512d00, 0x1c})
	github.com/ipfs/kubo@v0.20.0/plugin/loader/loader.go:187 +0xd9 fp=0xc0002ffa40 sp=0xc0002ff9c8 pc=0x2064499
github.com/ipfs/kubo/plugin/loader.(*PluginLoader).LoadDirectory(0xc000714f40, {0xc000512d00?, 0x3d58760?})
	github.com/ipfs/kubo@v0.20.0/plugin/loader/loader.go:163 +0xc6 fp=0xc0002ffab0 sp=0xc0002ffa40 pc=0x2064306
github.com/ipfs/kubo/plugin/loader.NewPluginLoader({0xc000718438, 0x14})
	github.com/ipfs/kubo@v0.20.0/plugin/loader/loader.go:115 +0x225 fp=0xc0002ffb58 sp=0xc0002ffab0 pc=0x2063c05
main.loadPlugins({0xc000718438?, 0x0?})
	github.com/ipfs/kubo@v0.20.0/cmd/ipfs/main.go:56 +0x25 fp=0xc0002ffba8 sp=0xc0002ffb58 pc=0x21955c5
main.mainRet.func2({0x2bf5b18?, 0xc000714f00}, 0xc00012b5e0)
	github.com/ipfs/kubo@v0.20.0/cmd/ipfs/main.go:159 +0xf4 fp=0xc0002ffc48 sp=0xc0002ffba8 pc=0x2195a54
github.com/ipfs/go-ipfs-cmds/cli.Run({0x2bf5b18?, 0xc00081ce40?}, 0x3d26d80, {0xc000052180, 0x3, 0x3}, 0x0?, 0xc00008f168?, 0xc000014020, 0x297a0c0, ...)
	github.com/ipfs/go-ipfs-cmds@v0.9.0/cli/run.go:107 +0x4d0 fp=0xc0002ffe38 sp=0xc0002ffc48 pc=0x2182e30
main.mainRet()
	github.com/ipfs/kubo@v0.20.0/cmd/ipfs/main.go:194 +0x5ba fp=0xc0002fff68 sp=0xc0002ffe38 pc=0x21962fa
main.main()
	github.com/ipfs/kubo@v0.20.0/cmd/ipfs/main.go:78 +0x19 fp=0xc0002fff80 sp=0xc0002fff68 pc=0x2195719
runtime.main()
	runtime/proc.go:250 +0x212 fp=0xc0002fffe0 sp=0xc0002fff80 pc=0xe363f2
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc0002fffe8 sp=0xc0002fffe0 pc=0xe69901

```
The full output is in the file attatched.
[KuboPluginCrash.txt](https://github.com/ipfs/go-ipfs-example-plugin/files/11855529/KuboPluginCrash.txt)

I looked around online and found a few posts in other projectds' forums about similar errors, but as this is basically my first time working with the go language I do not have the ability to figure out what is going wrong.

Platform:
x86_64 GNU/Linux

**Comment by hsanjuan** [comment]
I think Kubo is compiled with go1.19.10 and this error is related to using a newer version of go to compile the plugin.

**Comment by lidel** [comment]
@emendir  do you still get this error when using the latest go (0.20.x) and kubo (0.21.0) ?

**Comment by emendir** [comment]
Thanks for your suggestion.
I'm assuming you meant go 1.20.x instead of go 0.20.x
The result of testing go 1.20.5 together with kubo 0.21.0 was the following:

The `make build` step failed with the following error:
```
./set-target.sh v0.14.0
go build  -trimpath -buildmode=plugin -o "example-plugin.so" "main/main.go"
# github.com/lucas-clemente/quic-go/internal/qtls
~/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.27.1/internal/qtls/go119.go:6:13: cannot use "The version of quic-go you're using can't be built on Go 1.19 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.19 yet. F...) as int value in variable declaration
make: *** [Makefile:31: example-plugin.so] Error 1
```

As far as I understand it seems to be complaining that a dependency of kubo 0.21.0 doesn't yet work with go 1.19, from which I infer it won't doesn't with go 0.20.5 either.

**Comment by hsanjuan** [comment]
Just to clarify, the latest dist.ipfs.io releases of Kubo are built with go 1.19.10, so plugins need to be built with that.

You can build Kubo with a newer version of Go yourself, and then use that for the plugin too (I don't know if you did).

**Comment by aschmahmann** [comment]
@emendir did you try building kubo and the plugin with the same version of Go (as is required for Go plugins) as was suggested above? Note: the version of Go that kubo is built with on dist.ipfs.io is described in the build file https://dist.ipfs.tech/kubo/v0.21.0/build-info and kubo has `ipfs version --all` which will tell you the Go version as well.

**Comment by lidel** [comment]
iiuc Hector  provided useful README update in https://github.com/ipfs/go-ipfs-example-plugin/pull/30 about using the matching version of Go

Support for Go >1.20 is out of scope here (we will add support  when Go 1.21 is out, ETA Kubo 0.23).
